### ISSUE TITLE
Allow mapping by track name instead of requiring a specific output per track

### ISSUE THREAD

**Issue by mdwn** [mdwn/mtrack#23]
Track output channels should be optional and a mapping by track name should be configurable at the player level. For example, I should be able to define tracks `click`, `cue`, `backing-l`, and `backing-r` without an associated output channel per song. Then, in `mtrack.yaml`, I should be able to configure something along the lines of:

```
output_mapping:
  - track_name: source
    output_channel: 1
  - track_name: cue
    output_channel: 2
  - track_name: backing-l
    output_channel: 3
  - track_name: backing-r
    output_channel: 4
```
